id: P2F564383
initial_creation_type: ocr
source_metadata:
  volumes:
    b64d929ba3804411a0fc5ca6929df37d:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་ས་བཅུ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
